export class CatForm {
  constructor(
    public id: number,
    public submissionDate: string,
    public approved: boolean,
    public rejected: boolean,
    public rejectionReason: string,

    // APPLICANT INFORMATION
    public nameOfCat: string,
    public fname: string,
    public lname: string,
    public address: string,
    public city: string,
    public province: string,
    public postal_Code: string,
    public homePhone: string,
    public cellPhone: string,
    public email: string,
    public age: number,

    // YOUR FAMILY AND LIFESTYLE
    public personCatIsFor: string,
    public householdAgreement: boolean,
    public membersIntroduced: boolean,
    public catAllergies: boolean,
    public howManyAdults: number,
    public howManyChildren: number,
    public childrenAges: string,
    public childrenCatHandling: string,
    public childrenVisiting: boolean,
    public visitingFrequency: string,
    public childrenPrepared: string,
    public familyBusy: string,
    public familyActive: string,
    public scheduleRegularity: string,
    public familyPersonality: string,
    public plans: string,

    // YOUR HOME
    public typeOfResidence: string,
    public own: boolean,
    public landlordContact: string,
    public catsAllowed: boolean,
    public restrictions: string,
    public outdoorAreas: string,
    public typeOfStreet: string,
    public catHome: string,
    public livingSituationChanges: string,

    // CURRENT/PREVIOUS PETS
    public otherCats: boolean,
    public catsInfo: string,
    public catsAttitude: string,
    public otherPets: boolean,
    public otherPetsInfo: string,
    public spayedAndNeutered: number,
    public petLocation: string,
    public priorAdoption: boolean,
    public groupName: string,
    public surrenderedPet: boolean,
    public circumstances: string,
    public vetInfo: string,

    // NEW PET INFORMATION
    public expectations: string,
    public purpose: string,
    public primaryCaretaker: string,
    public hadCats: boolean,
    public vacationHome: string,
    public leftAloneWeekday: number,
    public leftAloneWeekend: number,
    public dailyExercise: number,
    public petAdjustment: number,
    public foodExpenses: number,
    public vetExpenses: number,
    public groomingExpenses: number,
    public boardingExpenses: number,
    public gender: boolean,
    public typeOfCoat: string,
    public catAge: string,
    public breedTypeColour: string,

    //Table
    public friendlyWithChildren: string,
    public friendlyWithDogs: string,
    public friendlyWithCats: string,
    public friendlyWithMe: string,
    public friendlyWithVisitors: string,
    public enjoyBeingGroomed: string,
    public enjoyBeingHeld: string,
    public enjoyBeingPetted: string,
    public becalm: string,
    public beActive: string,
    public bePlayful: string,
    public beQuiet: string,
    public beIndependent: string,
    public wakeMeUpAtNight: string,
    public aggressiveBehaviour: string,
    public beProtective: string,

    // Table 2
    public litterTrained: string,
    public declawed: string,
    public firstTimeOwner: string,
    public handleDifficultCat: string,
    public medical: boolean,
    public kittenHandling: boolean,
    public nailCare: string,
    public behaviouralIssue: string,
    public declaw: boolean,
    public catPast: string,
    public insurance: boolean,
    public giveUpCircumstances: string,
    public explainGiveUp: string,
    public additionalInfo: string,

    // REFERENCE1
    public ref1_fname: string,
    public ref1_lname: string,
    public ref1_relationship: string,
    public ref1_phonenumber: string,
    public ref1_email: string,

    // REFERENCE2
    public ref2_fname: string,
    public ref2_lname: string,
    public ref2_relationship: string,
    public ref2_phonenumber: string,
    public ref2_email: string,
    public findOutAbout: string
  ) {}
}
