export class CatForm {
  constructor(
    public id: number,
    public submissiondate: string,
    public approved: boolean,
    public rejected: boolean,
    public rejectionreason: string,

    // APPLICANT INFORMATION
    public ameofcat: string,
    public fname: string,
    public lname: string,
    public address: string,
    public city: string,
    public province: string,
    public postalcode: string,
    public homephone: string,
    public cellphone: string,
    public email: string,
    public age: number,

    // YOUR FAMILY AND LIFESTYLE
    public personcatisfor: string,
    public householdagreement: boolean,
    public membersintroduced: boolean,
    public catallergies: boolean,
    public howmanyadults: number,
    public howmanychild: number,
    public childrenages: string,
    public childrenhandling: string,
    public childrenvisit: boolean,
    public visitingfrequency: string,
    public childrenprepared: string,
    public  familybusy: string,
    public activefamily: string,
    public scheduleregularity: string,
    public familypersonality: string,
    public plans: string,

    // YOUR HOME
    public typeofresidence: string,
    public own: boolean,
    public landlordcontact: string,
    public catsallowed: boolean,
    public restrictions: string,
    public outdoorareas: string,
    public busystreet: string,
    public cathome: string,
    public livingsituationchanges: string,

    // CURRENT/PREVIOUS PETS
    public anycats: boolean,
    public catsinfo: string,
    public catattitude: string,
    public otherpets: boolean,
    public otherpetsinfo: string,
    public spayedandneutered: number,
    public animallocation: string,
    public  prioradoption: boolean,
    public groupname: string,
    public surrenderedanimal: boolean,
    public circumstances: string,
    public  vetinfo: string,

    // NEW PET INFORMATION
    public expectations: string,
    public mainpurpose: string,
    public primarycaretaker: string,
    public catsprior: boolean,
    public vacationhome: string,
    public leftaloneweekday: number,
    public leftaloneweekend: number,
    public  dailyexercise: number,
    public petadjustment: number,
    public foodexpenses: number,
    public vetexpenses: number,
    public groomingexpenses: number,
    public boardingexpenses: number,
    public gender: boolean,
    public catcoat: string,
    public catage: string,
    public breedtypecolour: string,

    //Table
    public friendlywithchild: string,
    public friendlywithdogs: string,
    public friendlywithcats: string,
    public friendlywithme: string,
    public friendlywithvisitors: string,
    public enjoybeinggroomed: string,
    public enjoybeingheld: string,
    public enjoybeingpetted: string,
    public becalm: string,
    public beactive: string,
    public beplayful: string,
    public bequiet: string,
    public  beindependant: string,
    public wakeupatnight: string,
    public aggressivebehaviour: string,
    public beprotective: string,

    // Table 2
    public littertrained: string,
    public declawed: string,
    public firsttimeowner: string,
    public handledifficultcat: string,
    public medicalhandling: boolean,
    public  kittenmedical: boolean,
    public nailcare: string,
    public behaviouralissues: string,
    public declawcat: boolean,
    public catpast: string,
    public catinsurance: boolean,
    public giveupcat: string,
    public catcirucumstances: string,
    public additionalinformation: string,

    // REFERENCE1
    public ref1fname: string,
    public ref1lname: string,
    public ref1relationship: string,
    public ref1phonenumber: string,
    public ref1email: string,

    // REFERENCE2
    public ref2fname: string,
    public ref2lname: string,
    public ref2relationship: string,
    public ref2phonenumber: string,
    public ref2email: string,
    public findoutanimal: string
  ) {}
}
